### ISSUE TITLE
No Artist or Album metadata when downloading full album in Flac format 

### ISSUE THREAD

**Issue by marco-boundi** [kmille/deezer-downloader#161]
Hi, when I download a full album or a song from Deezer I have no Artist or album metadata. Did I miss something in the config.ini ?

**Comment by marco-boundi** [comment]
I am downloading files in Flac format.

**Comment by marco-boundi** [comment]
I added a new pull request with the changes to enable metadata for FLAC files: https://github.com/kmille/deezer-downloader/pull/162

**Comment by kmille** [comment]
Do you really have this problem? Can you check it with vlc player?
There is an issue that a FLAC file has ID3 tags but it should have other tags (it's not called ID3-tags when using FLAC file format). VLC recognizes both.

**Comment by username227** [comment]
I just found this program. thank you. I am also looking for proper tagging in flac format. i'm getting everything without any tags at all. following.

**Comment by username227** [comment]
> Hey, I fixed this issue in [#162](https://github.com/kmille/deezer-downloader/pull/162). Can you please test? I could only test it with MP3 right now.

Can you merge the PR into a separate branch so that I can build the program with the changes to test? thanks!

**Comment by kmille** [comment]
You can checkout the `Add-flac-metadata` branch of this repo:
https://github.com/marco-boundi/deezer-downloader/tree/Add-flac-metadata

**Comment by kmille** [comment]
Then there are some bugs there. As I sayd: I coulnd't test it. Can you add some prints/logging there to figure out whats's wrong?

**Comment by username227** [comment]
not sure how to do that. can you be more specific? thanks.

**Comment by username227** [comment]
Seems to be the same as before...

**Comment by kmille** [comment]
What is your commit id you're using?

**Comment by username227** [comment]
7a4350718ec7a1984d1b0c770f5da4a051fd618f

**Comment by kmille** [comment]
Can you give me the whole command line output? Thanks!

**Comment by username227** [comment]
I assume you mean command line output when I try to run the program and download something. Here it is (note, as I said earlier, that despite the message, the song does download):
```
deezer-downloader -c /etc/deezer-downloader/config.ini                                                              ✔  10:33:47 AM   
Listening on 127.0.0.1:5000
WARNING:waitress.queue:Task queue depth is 1
WARNING:waitress.queue:Task queue depth is 1
User request: /search with {'type': 'track', 'query': 'george strait'}
User request: /search with {'type': 'album', 'query': 'george strait'}
User request: /download with {'type': 'album', 'music_id': 160165, 'add_to_playlist': False, 'create_zip': False}
Downloading '01 - George Strait Blue Clear Sky.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '02 - George Strait Carried Away.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '03 - George Strait Rockin' In The Arms Of Your Memory.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '04 - George Strait She Knows When You're On My Mind.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '05 - George Strait I Ain't Never Seen No One Like You.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '06 - George Strait I Can Still Make Cheyenne.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '07 - George Strait King Of The Mountain.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '08 - George Strait Do The Right Thing.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '09 - George Strait I'd Just As Soon Go.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
Downloading '10 - George Strait Need I Say More.flac'
Warning: Could not write song to disk: 'bytes' object has no attribute 'code'. Continuing with album...
```

**Comment by username227** [comment]
> ah, I forgot to add the file before committing/pushing.. Force pushed again. Can you try [232c9d7](https://github.com/kmille/deezer-downloader/commit/232c9d71571ff6c8920198b5ee0768ab58f135d7) again please?

YES! Thank you! Works now!!

Another, related feature request would be to give some options in the downloading of the tags - for example, the year is now saving as yyyy-dd-mm, which is not compatible with some players. An option to change it to a straight yyyy would be great; and the genre is not downloading. However, those are details that are not as important as the main thing that was accomplished today. Great work!

**Comment by kmille** [comment]
Can you check the album art? If you open it with VLC, it should be shown there

**Comment by kmille** [comment]
Regarding the genre: I couldn't find that information in the song metadata. Feel free to re-check that. Date should be fixed now. Can you check a5773313681c5ecf4b449b1407a439b5aab0d8f4 plase?

**Comment by username227** [comment]
No, it's regressed. The title is still present, but the other tags are gone, and I'm getting the following message when a song downloads:

Warning: Could not write song to disk: required argument is not an integer. Continuing with album...

**Comment by username227** [comment]
hmmm...on that one there are no tags at all. not even the original,  non-universal tags that VLC read. IMO you should commit what we had that worked, even with the year tag as is and you can work on that separately.
